### ISSUE TITLE
Can't get the example code working.

### ISSUE THREAD

**Issue by landland** [hawaiianchimp/sitemapper#13]
```
var sitemapper = new Sitemapper();

  sitemapper.timeout = 5000;
sitemapper.fetch('http://wp.seantburke.com/sitemap.xml')
  .then(function (data) {
    console.log(data);
  })
  .catch(function (error) {
    console.log(error);
  });
```

Output is

> { url: 'http://wp.seantburke.com/sitemap.xml', sites: [] }

Why is sites array empty?

**Comment by hawaiianchimp** [comment]
Which version are you running?

**Comment by hawaiianchimp** [comment]
Seems to be running okay on the latest version: sitemapper@v2.1.7 

https://tonicdev.com/57b1f189b055491400efd073/57b1f189b055491400efd074

**Comment by hawaiianchimp** [comment]
Try increasing the timeout from 5000 to 15000.
5000 means that if it doesn't see any results in 5 seconds, then it will return an empty array. Your connection might be slow.

**Comment by landland** [comment]
ok thanks! increasing the timeout worked.
