### ISSUE TITLE
Handling an empty sitemap file

### ISSUE THREAD

**Issue by edsyoo** [hawaiianchimp/sitemapper#23]
What if the sitemap URL and file are valid, but it contains no url's like below?

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</urlset>
```

**Comment by hawaiianchimp** [comment]
Hmm, not sure what happens, did you run into this issue?

**Comment by edsyoo** [comment]
I did, but [pull 21](https://github.com/hawaiianchimp/sitemapper/pull/21) might resolve the issue?   I used the below code to just test it out and I didn't receive anything from the promise, resolve or reject, which is kind of odd.  The xml file is just what's above (ie legit sitemap.xml with no URLs)
 
```
var Sitemapper = require('sitemapper'),
    sitemap = new Sitemapper(),
    url = 'http://testDomain.com/bad-sitemap.xml';

sitemap.fetch(url)
        .then(function(urls) {
                // console.log(urls.sites.length);
                console.log(urls);
                console.log('hii');

        })
        .catch(function(err) {
                console.log('hi');
                console.log(err);
        });
```

Is there any plans for getting the 2.1.10 version published to the public npm repo any time soon?

**Comment by hawaiianchimp** [comment]
Yeah I can publish tomorrow. I must have forgotten.

**Comment by edsyoo** [comment]
Actually, reopening because installing from npm, the patch from [PR 21](https://github.com/hawaiianchimp/sitemapper/pull/21) isn't showing up and the issue is not resolved.

**Comment by hawaiianchimp** [comment]
What version do you have installed?

**Comment by edsyoo** [comment]
2.1.12

**Comment by edsyoo** [comment]
*BUMP*

**Comment by edsyoo** [comment]
I was curious if this was going to get merged or applied to the lib/sitemapper.js file.

Another question is why it was applied to [the src/assets file](https://github.com/hawaiianchimp/sitemapper/blob/master/src/assets/sitemapper.js#L160) rather than to the [lib file](https://github.com/hawaiianchimp/sitemapper/blob/master/lib/sitemapper.js#L248)?  I am very new to this, so I am trying to learn.

Thanks,

**Comment by hawaiianchimp** [comment]
Oh I see what happened. Yeah the src/assets is written in es6, and the lib is compiled to es5, it should have been compiled to lib, but now that node can support es6 files, maybe compiling it isn't necessary anymore

**Comment by edsyoo** [comment]
So if I'm using node v6.10 and it's using ES5.1.281, how could I use the updated sitemapper version?

**Comment by hawaiianchimp** [comment]
If you run `npm run build` it will generate the correct lib file.

**Comment by hawaiianchimp** [comment]
Just ran it and committed it. It should be in NPM soon
